datasource:
  jswms:
    #监控统计拦截的filters
    filters: stat
    driverClassName: com.mysql.jdbc.Driver
    #配置基本属性
    url: jdbc:mysql://192.168.0.127:3306/jswms?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: root
    password: aa123456
    #配置初始化大小/最小/最大
    initialSize: 1
    minIdle: 1
    maxActive: 20
    #获取连接等待超时时间
    maxWait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
  wms:
    #监控统计拦截的filters
    filters: stat
    driverClassName: com.mysql.jdbc.Driver
    #配置基本属性
    url: jdbc:mysql://192.168.0.127:3306/wms?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: root
    password: aa123456
    #配置初始化大小/最小/最大
    initialSize: 1
    minIdle: 1
    maxActive: 20
    #获取连接等待超时时间
    maxWait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
  sms:
    #监控统计拦截的filters
    filters: stat
    driverClassName: com.mysql.jdbc.Driver
    #配置基本属性
    url: jdbc:mysql://192.168.0.127:3306/sms?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: root
    password: aa123456
    #配置初始化大小/最小/最大
    initialSize: 1
    minIdle: 1
    maxActive: 20
    #获取连接等待超时时间
    maxWait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20

management:
  endpoints:
    web:
      exposure:
        include: "*"