package com.tastycai.multidatasource.sms.dao;

import com.tastycai.multidatasource.sms.model.Product;
import com.tastycai.multidatasource.sms.model.ProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_product
     *
     * @mbg.generated Sun Aug 04 15:32:16 CST 2019
     */
    long countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_product
     *
     * @mbg.generated Sun Aug 04 15:32:16 CST 2019
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_product
     *
     * @mbg.generated Sun Aug 04 15:32:16 CST 2019
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_product
     *
     * @mbg.generated Sun Aug 04 15:32:16 CST 2019
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_product
     *
     * @mbg.generated Sun Aug 04 15:32:16 CST 2019
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_product
     *
     * @mbg.generated Sun Aug 04 15:32:16 CST 2019
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_product
     *
     * @mbg.generated Sun Aug 04 15:32:16 CST 2019
     */
    Product selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_product
     *
     * @mbg.generated Sun Aug 04 15:32:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_product
     *
     * @mbg.generated Sun Aug 04 15:32:16 CST 2019
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_product
     *
     * @mbg.generated Sun Aug 04 15:32:16 CST 2019
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_product
     *
     * @mbg.generated Sun Aug 04 15:32:16 CST 2019
     */
    int updateByPrimaryKey(Product record);
}