package com.tastycai.multidatasource.jswms.dao;

import com.tastycai.multidatasource.jswms.model.StockOccupy;
import com.tastycai.multidatasource.jswms.model.StockOccupyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockOccupyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    long countByExample(StockOccupyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    int deleteByExample(StockOccupyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    int deleteByPrimaryKey(Integer stockOccupyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    int insert(StockOccupy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    int insertSelective(StockOccupy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    List<StockOccupy> selectByExample(StockOccupyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    StockOccupy selectByPrimaryKey(Integer stockOccupyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") StockOccupy record, @Param("example") StockOccupyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    int updateByExample(@Param("record") StockOccupy record, @Param("example") StockOccupyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    int updateByPrimaryKeySelective(StockOccupy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    int updateByPrimaryKey(StockOccupy record);
}