package com.tastycai.multidatasource.wms.model;

public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_stock.stock_id
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    private Integer stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_stock.warehouse_code
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    private String warehouseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_stock.product_id
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_stock.product_code
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_stock.stock_number
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    private Integer stockNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_stock.stock_id
     *
     * @return the value of wms_stock.stock_id
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_stock.stock_id
     *
     * @param stockId the value for wms_stock.stock_id
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_stock.warehouse_code
     *
     * @return the value of wms_stock.warehouse_code
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_stock.warehouse_code
     *
     * @param warehouseCode the value for wms_stock.warehouse_code
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_stock.product_id
     *
     * @return the value of wms_stock.product_id
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_stock.product_id
     *
     * @param productId the value for wms_stock.product_id
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_stock.product_code
     *
     * @return the value of wms_stock.product_code
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_stock.product_code
     *
     * @param productCode the value for wms_stock.product_code
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_stock.stock_number
     *
     * @return the value of wms_stock.stock_number
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    public Integer getStockNumber() {
        return stockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_stock.stock_number
     *
     * @param stockNumber the value for wms_stock.stock_number
     *
     * @mbg.generated Sun Aug 04 15:27:56 CST 2019
     */
    public void setStockNumber(Integer stockNumber) {
        this.stockNumber = stockNumber;
    }
}