package com.tastycai.multidatasource.jswms.model;

import java.util.ArrayList;
import java.util.List;

public class StockOccupyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public StockOccupyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStockOccupyIdIsNull() {
            addCriterion("stock_occupy_id is null");
            return (Criteria) this;
        }

        public Criteria andStockOccupyIdIsNotNull() {
            addCriterion("stock_occupy_id is not null");
            return (Criteria) this;
        }

        public Criteria andStockOccupyIdEqualTo(Integer value) {
            addCriterion("stock_occupy_id =", value, "stockOccupyId");
            return (Criteria) this;
        }

        public Criteria andStockOccupyIdNotEqualTo(Integer value) {
            addCriterion("stock_occupy_id <>", value, "stockOccupyId");
            return (Criteria) this;
        }

        public Criteria andStockOccupyIdGreaterThan(Integer value) {
            addCriterion("stock_occupy_id >", value, "stockOccupyId");
            return (Criteria) this;
        }

        public Criteria andStockOccupyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock_occupy_id >=", value, "stockOccupyId");
            return (Criteria) this;
        }

        public Criteria andStockOccupyIdLessThan(Integer value) {
            addCriterion("stock_occupy_id <", value, "stockOccupyId");
            return (Criteria) this;
        }

        public Criteria andStockOccupyIdLessThanOrEqualTo(Integer value) {
            addCriterion("stock_occupy_id <=", value, "stockOccupyId");
            return (Criteria) this;
        }

        public Criteria andStockOccupyIdIn(List<Integer> values) {
            addCriterion("stock_occupy_id in", values, "stockOccupyId");
            return (Criteria) this;
        }

        public Criteria andStockOccupyIdNotIn(List<Integer> values) {
            addCriterion("stock_occupy_id not in", values, "stockOccupyId");
            return (Criteria) this;
        }

        public Criteria andStockOccupyIdBetween(Integer value1, Integer value2) {
            addCriterion("stock_occupy_id between", value1, value2, "stockOccupyId");
            return (Criteria) this;
        }

        public Criteria andStockOccupyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("stock_occupy_id not between", value1, value2, "stockOccupyId");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNull() {
            addCriterion("product_code is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNotNull() {
            addCriterion("product_code is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeEqualTo(String value) {
            addCriterion("product_code =", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotEqualTo(String value) {
            addCriterion("product_code <>", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThan(String value) {
            addCriterion("product_code >", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("product_code >=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThan(String value) {
            addCriterion("product_code <", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThanOrEqualTo(String value) {
            addCriterion("product_code <=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLike(String value) {
            addCriterion("product_code like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotLike(String value) {
            addCriterion("product_code not like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIn(List<String> values) {
            addCriterion("product_code in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotIn(List<String> values) {
            addCriterion("product_code not in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeBetween(String value1, String value2) {
            addCriterion("product_code between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotBetween(String value1, String value2) {
            addCriterion("product_code not between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andOccupyNumberIsNull() {
            addCriterion("occupy_number is null");
            return (Criteria) this;
        }

        public Criteria andOccupyNumberIsNotNull() {
            addCriterion("occupy_number is not null");
            return (Criteria) this;
        }

        public Criteria andOccupyNumberEqualTo(Integer value) {
            addCriterion("occupy_number =", value, "occupyNumber");
            return (Criteria) this;
        }

        public Criteria andOccupyNumberNotEqualTo(Integer value) {
            addCriterion("occupy_number <>", value, "occupyNumber");
            return (Criteria) this;
        }

        public Criteria andOccupyNumberGreaterThan(Integer value) {
            addCriterion("occupy_number >", value, "occupyNumber");
            return (Criteria) this;
        }

        public Criteria andOccupyNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("occupy_number >=", value, "occupyNumber");
            return (Criteria) this;
        }

        public Criteria andOccupyNumberLessThan(Integer value) {
            addCriterion("occupy_number <", value, "occupyNumber");
            return (Criteria) this;
        }

        public Criteria andOccupyNumberLessThanOrEqualTo(Integer value) {
            addCriterion("occupy_number <=", value, "occupyNumber");
            return (Criteria) this;
        }

        public Criteria andOccupyNumberIn(List<Integer> values) {
            addCriterion("occupy_number in", values, "occupyNumber");
            return (Criteria) this;
        }

        public Criteria andOccupyNumberNotIn(List<Integer> values) {
            addCriterion("occupy_number not in", values, "occupyNumber");
            return (Criteria) this;
        }

        public Criteria andOccupyNumberBetween(Integer value1, Integer value2) {
            addCriterion("occupy_number between", value1, value2, "occupyNumber");
            return (Criteria) this;
        }

        public Criteria andOccupyNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("occupy_number not between", value1, value2, "occupyNumber");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 04 15:32:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jswms_stock_occupy
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}