package com.tastycai.multidatasource.jswms.model;

public class StockOccupy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jswms_stock_occupy.stock_occupy_id
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    private Integer stockOccupyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jswms_stock_occupy.product_id
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jswms_stock_occupy.product_code
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jswms_stock_occupy.occupy_number
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    private Integer occupyNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jswms_stock_occupy.stock_occupy_id
     *
     * @return the value of jswms_stock_occupy.stock_occupy_id
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public Integer getStockOccupyId() {
        return stockOccupyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jswms_stock_occupy.stock_occupy_id
     *
     * @param stockOccupyId the value for jswms_stock_occupy.stock_occupy_id
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public void setStockOccupyId(Integer stockOccupyId) {
        this.stockOccupyId = stockOccupyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jswms_stock_occupy.product_id
     *
     * @return the value of jswms_stock_occupy.product_id
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jswms_stock_occupy.product_id
     *
     * @param productId the value for jswms_stock_occupy.product_id
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jswms_stock_occupy.product_code
     *
     * @return the value of jswms_stock_occupy.product_code
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jswms_stock_occupy.product_code
     *
     * @param productCode the value for jswms_stock_occupy.product_code
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jswms_stock_occupy.occupy_number
     *
     * @return the value of jswms_stock_occupy.occupy_number
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public Integer getOccupyNumber() {
        return occupyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jswms_stock_occupy.occupy_number
     *
     * @param occupyNumber the value for jswms_stock_occupy.occupy_number
     *
     * @mbg.generated Sun Aug 04 15:32:43 CST 2019
     */
    public void setOccupyNumber(Integer occupyNumber) {
        this.occupyNumber = occupyNumber;
    }
}